---
title: "Probabilidades"
output: 
  html_document:
    toc: false
---

```{r setup, include = FALSE, cache = FALSE}
source("knitr_setup.R")
```


 <!-- <div class="alert alert-danger" role="alert"> -->
 <!-- </div> -->

# Disciplinas

A página abrange o conteúdo das seguintes disciplinas e cursos ofertados:

- **CE0035 - Cálculo de Probabilidades A**:
  - Licenciatura em Matemática (MA) - Noturno

# Detalhes da oferta da disciplina

- **Período:** Primeiro semestre de 2020
- **Professor Responsável:**
    - Luan Demarco Fiorentin - DEST/UFPR
    - Contato: luanfiorentin@hotmail.com
- **Horários e Locais:**
  - Matemática (MA):
    - Terça-feira, 19:00 - 20:30h (Sala PA-07)
    - Quinta-feira, 20:45 - 22:15h (Sala PA-07)
- **Horários de atendimento do professor:**
    - Sexta-feira, 10:00-11:30h e 13:30-15:00h (preferenciais) 
    - Outros horários podem ser agendados previamente por email
- **Frequência**: De acordo com as normas da UFPR, mínimo de 75% de presença
- **Avaliações**:
  - As duas provas serão realizadas em sala de aula
  - **Média Final (MF)**: a média final será composta pela média geral simples
  - $MF = (P1 + P2) / 2$
- **Segunda chamada**:
  - Somente as provas discursivas poderão ter segunda chamada
    - Só será realizada segunda chamada para alunos que protocolarem o
      pedido, devidamente justificado, junto ao Departamento de
      Estatística
    - As provas de segunda chamada serão realizadas em comum acordo entre 
      o aluno e o professor
- **Datas importantes:** De acordo com a [Resolução 64/18 - CEPE][]:
    - **02/03**: Início do segundo semestre letivo
    - **27/06**: Final do segundo semestre letivo
    - **06/07-11/07**: Período de exames finais

# Programa/objetivos da disciplina

O objetivo desta disciplina é capacitar os alunos em conceitos básicos
de probabilidade. O curso compreende quatro grandes tópicos:

- Teoria dos conjuntos e análise combinatória.
  - Espaço amostral e Eventos; 
  - Operações com conjuntos; 
  - Combinações e Permutações; 
  - Sigma-Álgebra. 
- Conceitos de probabilidades e axiomas de Kolmogorov.
  - Definição Clássica, Frequentista, Geomética e Axiomática; 
  - Probabilidade condicional; 
  - Independência de eventos; 
  - Regra do produto de probabilidades; 
  - Lei da Probabilidade Total; 
  - Teorema de Bayes. 
- Variáveis aleatórias unidimensionais e distribuições de probabilidades.
  - Variável aleatória discreta e contínua; 
  - Função de distribuição; 
  - Função de densidade de probabilidade; 
  - Função de probabilidade; 
  - Função de distribuição mista; 
  - Principais modelos discretos: 
    - Uniforme Discreto; 
    - Bernoulli; 
    - Binomial; 
    - Geométrico; 
    - Binomial Negativo; 
    - Hipergeométrico. 
  - Principais modelos contínuos: 
    - Uniforme Contínuo; 
    - Exponencial; 
    - Gamma; 
    - Normal. 
- Esperança e Variância.
  - Esperança: caso discreto e contínuo; 
  - Variância: caso discreto e contínuo; 
  - Propriedades. 

<!-- links -->

[Resolução 24/19 - CEPE]: http://www.est.ufpr.br/arquivos/cepe-24.19.pdf